# Generated by Django 4.0.2 on 2022-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active')], max_length=100, null=True),
        ),
    ]
