# Generated by Django 4.0.2 on 2022-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expmonth', models.CharField(max_length=100)),
                ('expyear', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
            ],
        ),
    ]
