# Generated by Django 4.0.2 on 2022-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0006_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
