# Generated by Django 4.0.2 on 2022-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0007_user_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
