# Generated by Django 4.0.2 on 2022-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0008_user_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('reject', 'reject')], max_length=100, null=True),
        ),
    ]
