# Generated by Django 4.0.2 on 2022-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0009_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('packed', 'packed'), ('unpacked', 'unpacked')], max_length=100, null=True),
        ),
    ]
